
<table border="1">
        <tr>
            <td>PHP</td>
            <td><?php echo $this->phpVersion;  ?></td>
        </tr>
        <tr>
            <td>Auteur</td>
            <td><?php echo $this->auteur; ?></td>
        </tr>
        <tr>
            <td>Serveur</td>
            <td><?php echo $_SERVER['SERVER_NAME'];?></td>
        </tr>
        <tr>
            <td>Port</td>
            <td><?php echo $_SERVER['SERVER_PORT'];?></td>
        </tr>
    </table>
